"""add_type_field_to_video_slices_for_full_or_fragment

Revision ID: 7c8fc573c2e4
Revises: 61d5bd275ad2
Create Date: 2025-08-17 13:54:38.966954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c8fc573c2e4'
down_revision: Union[str, Sequence[str], None] = '61d5bd275ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_slices', sa.Column('type', sa.String(50), nullable=True))
    # Set default value for existing records
    op.execute("UPDATE video_slices SET type = 'fragment' WHERE type IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_slices', 'type')
    # ### end Alembic commands ###
