"""add thumbnail_path to videos

Revision ID: 8f3b9d8a4c2e
Revises: 7c8fc573c2e4
Create Date: 2025-08-19 15:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f3b9d8a4c2e'
down_revision = '7c8fc573c2e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('thumbnail_path', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'thumbnail_path')
    # ### end Alembic commands ###